project:
  type: website
  output-dir: _site

website:
  title: "Test Plotly"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: notes.qmd
        text: Sample Notes

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



